// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9fbczI0KMkvJmu48EDFhTv4Be20d2z60',
    appId: '1:887053802738:web:e9b6560b967d246076846b',
    messagingSenderId: '887053802738',
    projectId: 'bookswap-ab258',
    authDomain: 'bookswap-ab258.firebaseapp.com',
    storageBucket: 'bookswap-ab258.firebasestorage.app',
    measurementId: 'G-LLJP0BJT5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1tYWBB9ebCKaxv9_uojcO78AlaAHikI',
    appId: '1:887053802738:android:173db8ddcbf8e21c76846b',
    messagingSenderId: '887053802738',
    projectId: 'bookswap-ab258',
    storageBucket: 'bookswap-ab258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7K-covVlJUGcNjj9AyTvQICMqjXm54eQ',
    appId: '1:887053802738:ios:f4e1b81e2c538ce276846b',
    messagingSenderId: '887053802738',
    projectId: 'bookswap-ab258',
    storageBucket: 'bookswap-ab258.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7K-covVlJUGcNjj9AyTvQICMqjXm54eQ',
    appId: '1:887053802738:ios:f4e1b81e2c538ce276846b',
    messagingSenderId: '887053802738',
    projectId: 'bookswap-ab258',
    storageBucket: 'bookswap-ab258.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9fbczI0KMkvJmu48EDFhTv4Be20d2z60',
    appId: '1:887053802738:web:afa12a9f2863d0e376846b',
    messagingSenderId: '887053802738',
    projectId: 'bookswap-ab258',
    authDomain: 'bookswap-ab258.firebaseapp.com',
    storageBucket: 'bookswap-ab258.firebasestorage.app',
    measurementId: 'G-00SSRKBGJ6',
  );
}
